osx_image: xcode10.2

language: objective-c
cache:
  - bundler
  - cocoapods

dependencies:
  build:
    - ruby:2.4.5

build_targets:
  - name: abtesting
    tags:
      os: osx
    environment:
      - SAMPLE=ABTesting
      - PODFILE=abtesting/Podfile
    commands:
      - gem update --system
      - gem install bundler
      - cd ABTesting
      - bundle install
      - gem install xcpretty
      - bundle exec pod install --repo-update
      - cp ../mock-GoogleService-Info.plist ./GoogleService-Info.plist
      # Needed for this syntax of sed, per https://stackoverflow.com/questions/18620153/find-matching-text-and-replace-next-line.
      - gsed -i /<key>BUNDLE_ID</{n;s/id/com.google.firebase.quickstart.ABTestingExample/;} GoogleService-Info.plist
      - gsed -i s/YOUR_REVERSED_CLIENT_ID/com.googleusercontent.apps.123456789000-hjugbg6ud799v4c49dim8ce2usclthar/ ABTestingExample/Info.plist
      - gem install xcodeproj
      - ruby ../info_script.rb ABTesting
      - cd ..
      - ./test.sh


#matrix:
#  include:
#  - podfile: abtesting/Podfile
#    env: SAMPLE=ABTesting
#  - podfile: admob/Podfile
#    env: before_install:SAMPLE=AdMob
#  - podfile: analytics/Podfile
#    env: SAMPLE=Analytics
#  - podfile: authentication/Podfile
#    env: SAMPLE=Authentication
#  - podfile: config/Podfile
#    env: SAMPLE=Config
#  - podfile: crashlytics/Podfile
#    env: SAMPLE=Crashlytics
#  - podfile: crashreporting/Podfile
#    env: SAMPLE=CrashReporting
#  - podfile: database/Podfile
#    env: SAMPLE=Database
#  - podfile: dynamiclinks/Podfile
#    env: SAMPLE=DynamicLinks
#  - podfile: firestore/Podfile
#    env: SAMPLE=Firestore
#  - podfile: functions/Podfile
#    env: SAMPLE=Functions
#  - podfile: messaging/Podfile
#    env: SAMPLE=Messaging
#  - podfile: mlmodelinterpreter/Podfile
#    env: SAMPLE=MLModelInterpreter
#  - podfile: mlvision/Podfile
#    env: SAMPLE=MLVision
#  - podfile: performance/Podfile
#    env: SAMPLE=Performance
#  - podfile: storage/Podfile
#    env: SAMPLE=Storage

#before_install:
#  - cd $SAMPLE
#  - bundle install
#  - gem install xcpretty
#  - bundle exec pod install --repo-update
#  - cp ../mock-GoogleService-Info.plist ./GoogleService-Info.plist
#  - sed -i '' '/<key>BUNDLE_ID</{n;s/id/com.google.firebase.quickstart.'$SAMPLE'Example/;}' GoogleService-Info.plist
#  - sed -i '' 's/YOUR_REVERSED_CLIENT_ID/com.googleusercontent.apps.123456789000-hjugbg6ud799v4c49dim8ce2usclthar/' "$SAMPLE"Example/Info.plist
#  - gem install xcodeproj
#  - ruby ../info_script.rb $SAMPLE
#  - cd -

#script: ./test.sh
#
#branches:
#  only:
#    - master
